"""KBZPay Receive-QR string generator.

Format reverse-engineered from KBZPay 5.8.5 (see kbzpay-qr-notes.html):

    QR = base64(42-byte TLV) + "F" + checksum_char + hex(server_time_ms) + "=="

TLV layout (42 bytes):
    85 06 "KBZPay"            magic header
    61 40 4f 02 f0 50 02 10   template bytes (constant)
    51 02 31 31 57 16
    <6 bytes BCD phone>       11 digits + one 0xD pad nibble
    26 09 10 10 1f 9f 08 04   template bytes (constant)
    01 01 9f 24 01 30

The phone field is fixed width, so the digit count is not free: 11 digits fill it
exactly. Shorter numbers are padded with further 0xD nibbles, which keeps the tail
template aligned but is UNVERIFIED against KBZPay's server — the 42-byte payload
is generated server-side (the app only appends the timestamp suffix), so there is
no client-side encoder to confirm the padding rule from. Callers gate this behind
``config.KBZPAY_ALLOW_SHORT_NUMBERS``.
"""

import base64
import re
import time

BASE64_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

MAGIC = bytes.fromhex("85064b425a506179")
ROUTE = bytes.fromhex("4f02f0500210")
NO_AMOUNT_META = bytes.fromhex("51023131")
PHONE_TAG = bytes.fromhex("5716")
POST_PHONE = bytes.fromhex("260910101f9f08040101")
AMOUNT_TAG = bytes.fromhex("9f24")

# Compatibility aliases for the verified, phone-only 42-byte format.
HEAD = MAGIC + bytes.fromhex("6140") + ROUTE + NO_AMOUNT_META + PHONE_TAG
TAIL = POST_PHONE + AMOUNT_TAG + bytes.fromhex("0130")

#: The BCD phone field is 6 bytes, i.e. 12 half-byte digits.
PHONE_FIELD_NIBBLES = 12

#: HEAD (22) + phone field (6) + TAIL (14).
TLV_LENGTH = 42

_ASCII_DIGITS_RE = re.compile(r"[0-9]+")


class KbzPayPayloadError(ValueError):
    """The phone number cannot be packed into KBZPay's fixed-width BCD field."""


def _bcd(phone: str) -> bytes:
    if not _ASCII_DIGITS_RE.fullmatch(phone):
        raise KbzPayPayloadError(f"phone must be ASCII digits only, got {phone!r}")
    if len(phone) > PHONE_FIELD_NIBBLES:
        raise KbzPayPayloadError(
            f"phone has {len(phone)} digits, field holds {PHONE_FIELD_NIBBLES}"
        )
    digits = phone.ljust(PHONE_FIELD_NIBBLES, "D")
    return bytes(int(digits[i : i + 2], 16) for i in range(0, len(digits), 2))


def _amount_tlv(phone: str, amount: int) -> bytes:
    amount_bytes = f"{amount}.0".encode("ascii")
    if len(amount_bytes) > 0xFF:
        raise KbzPayPayloadError("amount is too long for the KBZPay field")

    body = (
        ROUTE
        + PHONE_TAG
        + _bcd(phone)
        + POST_PHONE
        + AMOUNT_TAG
        + bytes([len(amount_bytes)])
        + amount_bytes
    )
    total_length = len(MAGIC) + 2 + len(body)
    encoded_length = (total_length - 10) * 2
    if not 0 <= encoded_length <= 0xFF:
        raise KbzPayPayloadError("payload is too long for the KBZPay length field")
    return MAGIC + bytes([0x61, encoded_length]) + body


def kbzpay_qr_string(
    phone: str, ts_ms: int | None = None, amount: int | None = None
) -> str:
    ts = ts_ms if ts_ms is not None else int(time.time() * 1000)
    if amount is None:
        tlv = HEAD + _bcd(phone) + TAIL
        if len(tlv) != TLV_LENGTH:
            # A shifted tail makes the server read a different number, so refuse rather
            # than hand back a QR that points at the wrong account.
            raise KbzPayPayloadError(f"TLV is {len(tlv)} bytes, expected {TLV_LENGTH}")
    else:
        if isinstance(amount, bool) or not isinstance(amount, int) or amount <= 0:
            raise KbzPayPayloadError("amount must be a positive whole number")
        tlv = _amount_tlv(phone, amount)

    payload = base64.b64encode(tlv).decode()
    checksum = BASE64_ALPHABET[sum(int(d) for d in str(ts)) % 64]
    suffix = f"F{checksum}{ts:x}"
    # Preserve the verified legacy output byte-for-byte. Amount samples generated by
    # KBZPay end after the timestamp; any '=' before F belongs to the TLV's base64.
    return f"{payload}{suffix}==" if amount is None else f"{payload}{suffix}"
